### ISSUE TITLE
fails with node core modules

### ISSUE THREAD

**Issue by sindhus** [jfhbrook/browserify-cdn#101]
![requirebin - http___requirebin com_](https://cloud.githubusercontent.com/assets/4291156/6962511/af514372-d952-11e4-91f0-b69ef32c6465.png)

**Comment by JamesKyburz** [comment]
I think this is related to issue #100

**Comment by jfhbrook** [comment]
I think so too.

I haven't had time to look into this, but I can give some hints. Most likely spawn is trying to spawn browserify, though it's possible it's trying to spawn npm. Why it wouldn't be able to find either one of them, or why it would matter whether you're trying to bundle something core vs non-core, I can't even begin to imagine.
