### ISSUE TITLE
502 - bad gateway at wzrd.in

### ISSUE THREAD

**Issue by nolanlawson** [jfhbrook/browserify-cdn#106]
Just letting you know https://wzrd.in/ seems down:

```
502 Bad Gateway
nginx/1.7.8
```

**Comment by greenify** [comment]
Can we put "use an auto-delete script" (as a temporary workaround) on the high priority list? :)

**Comment by jfhbrook** [comment]
auto delete what?

**Comment by greenify** [comment]
sorry. I was referring to the unused, old cache - as mentioned in #103  ;-)

**Comment by jfhbrook** [comment]
See: https://github.com/jfhbrook/browserify-cdn/issues/103
